resource "aws_sfn_state_machine" "on_file_created_handler" {
  name     = "${var.project-name}-sfn-on-file-created-handler"
  role_arn = aws_iam_role.on_file_created_handler.arn

  definition = jsonencode({
    Comment = "SFN to handle on-file-created event generated by EventBridge",
    StartAt = "GetObject",
    States = {
      GetObject = {
        Type = "Task",
        Arguments = {
          Bucket = "{% $states.input.bucket %}",
          Key    = "{% $states.input.key %}",
          Range  = "bytes=0-15"
        },
        Output = {
          refData  = "{% $substring($states.result.Body, 0, 8) %}",
          dataType = "{% $substring($states.result.Body, 8, 16) %}"
        },
        Resource = "arn:aws:states:::aws-sdk:s3:getObject",
        End      = true
      }
    },
    QueryLanguage = "JSONata"
  })
}